/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface VrfKeyPair {
  publicKey: string
  secretKey: string
}
export interface VrfProofOutput {
  proof: string
  output: string
}
export declare function generateKeypairFromSeed(seed: string): VrfKeyPair
export declare function vrfProve(
  secretKey: string,
  message: string,
  auxData?: string | undefined | null,
): VrfProofOutput
export declare function vrfVerify(
  publicKey: string,
  message: string,
  proof: string,
  output: string,
  auxData?: string | undefined | null,
): boolean
export declare function vrfProofToHash(proof: string): string
